server:
  port: 8085

spring:
  application:
    name: claims-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/claimsdb}
    username: ${SPRING_DATASOURCE_USERNAME:insurai}
    password: ${SPRING_DATASOURCE_PASSWORD:insurai123}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    group-id: claims-service-group
