server:
  port: 8086

spring:
  application:
    name: renewal-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/renewaldb}
    username: ${SPRING_DATASOURCE_USERNAME:insurai}
    password: ${SPRING_DATASOURCE_PASSWORD:insurai123}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    group-id: renewal-service-group
